#  ----------------------------------------------------------------------------
# This action / workflow:
# - executed on: macOS, linux and windows
# - checksout the source
# - installs some requirements
# - installs some more requirements on linux
# - builds using electron-builder
# - releases if properly tagged
#
# Using: https://github.com/marketplace/actions/electron-builder-action
#  ----------------------------------------------------------------------------

name: electron_builder

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install bsdtar rpm on Linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install bsdtar rpm

      - name: Install snapcraft
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo snap install snapcraft --classic 

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
