#  ----------------------------------------------------------------------------
# This action / workflow:
# - checks for stale issues
# - and pull requests
# - labels them stale after x days
# - closed them after Y days
#
# Using: https://github.com/marketplace/actions/close-stale-issues
#  ----------------------------------------------------------------------------

name: mark_stale

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue seems to be stale'
        stale-pr-message: 'This pull request seems to be stale'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 90
        days-before-close: 365
