#  ----------------------------------------------------------------------------
# This action / workflow:
# - executes npm audit
# - on each push to the master branch
#
# Using: https://github.com/marketplace/actions/npm-audit-action
#  ----------------------------------------------------------------------------

name: npm_audit

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
